# Generated by Django 2.0 on 2017-12-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='watch',
            new_name='product',
        ),
    ]
