# Generated by Django 2.0 on 2018-01-02 01:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watch', '0002_auto_20171216_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
