# Generated by Django 2.0 on 2018-01-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_auto_20180106_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
